# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bestagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bestagram
  pod 'Cache'
  pod 'AlamofireImage', '~> 4.1'

  target 'BestagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BestagramUITests' do
    # Pods for testing
  end

end